# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_body', models.TextField()),
                ('blog_type', models.CharField(max_length=50)),
                ('blog_timestamp', models.DateTimeField()),
                ('blog_imgurl', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_author', models.CharField(max_length=20, null=True)),
                ('blog_ismarkdown', models.CharField(max_length=1, null=True)),
                ('blog_like', models.IntegerField(null=True)),
                ('blog_clicknum', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
